---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: aspnet-api-domain
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: aspnet-api-domain
    template:
      metadata:
        labels:
          app: aspnet-api-domain
      spec:
        containers:
        - name: aspnet-api-domain
          image: jfantauzzi/domainapi2020
          ports:
            - containerPort: 80
              name: aspnet-api-domain-http