---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: aspnet-dom
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: aspnet-dom
    template:
      metadata:
        labels:
          app: aspnet-dom
      spec:
        containers:
        - name: aspnet-dom
          image: jfantauzzi/domainapi2020
          ports:
            - containerPort: 80
              name: domain-http