jobs:
  # BUILD
  build_angular:
    defaults:
      run:
        working-directory: StarDex.AngularClient/ #does it need to be in ng10 folder
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: npm ci #clean-install
      - run: npm run build
      - run: npm run lint

  build_img_api:
    defaults:
      run:
        working-directory: Image.Service/
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore
      - run: dotnet build --no-restore
  
  build_domain_api:
    defaults:
      run:
        working-directory: Domain.Service/
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore
      - run: dotnet build --no-restore

  build_mvc:
    defaults:
      run:
        working-directory: StarDex.MVCClient/
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore
      - run: dotnet build --no-restore

  # TEST
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet test Domain.Service/DomainService.Testing/*.csproj
      - run: dotnet test Image.Service/Image.Testing/*.csproj

  # ANALYZE
  analyze_image_api:
    needs: [build_img_api, test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --unshallow
      - run: dotnet tool install --global dotnet-sonarscanner
      - run: |
          dotnet sonarscanner begin -o:'jpchionglo' -k:'revadeximageservice' -d:sonar.login='${{ secrets.SONARLOGINIMAGE }}' -d:sonar.host.url='https://sonarcloud.io'
          dotnet build Image.Service/ImageService.sln
          dotnet test Image.Service/Image.Testing/*.csproj -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --logger trx
          dotnet sonarscanner end -d:sonar.login='${{ secrets.SONARLOGINIMAGE }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  analyze_domain_api:
    needs: [build_domain_api, test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --unshallow
      - run: dotnet tool install --global dotnet-sonarscanner
      - run: |
          dotnet sonarscanner begin -o:'jpchionglo' -k:'revadexdomainservice' -d:sonar.login='${{ secrets.SONARLOGINDOMAIN }}' -d:sonar.host.url='https://sonarcloud.io'
          dotnet build Domain.Service/DomainService.sln
          dotnet test Domain.Service/DomainService.Testing/*.csproj -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --logger trx
          dotnet sonarscanner end -d:sonar.login='${{ secrets.SONARLOGINDOMAIN }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  analyze_mvc:
    needs: [build_mvc, test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --unshallow
      - run: dotnet tool install --global dotnet-sonarscanner
      - run: |
          dotnet sonarscanner begin -o:'jpchionglo' -k:'revadexstardexclient' -d:sonar.login='${{ secrets.SONARLOGINCLIENT }}' -d:sonar.host.url='https://sonarcloud.io/'
          dotnet build StarDex.MVCClient/StarDexClient.sln
          dotnet sonarscanner end -d:sonar.login='${{ secrets.SONARLOGINCLIENT }}'
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                 
  # PACK
  pack_angular:
    defaults:
      run:
        working-directory: StarDex.AngularClient/
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    needs: build_angular
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
        - run: echo ${DOCKER_TOKEN} | docker login -u ${DOCKER_LOGIN} --password-stdin
        - run: docker image build -f ../.docker/AngularClient.dockerfile -t angular .
        - run: docker image tag angular jfantauzzi/ng2020
        - run: docker image push jfantauzzi/ng2020
        - run: docker logout

  pack_image_api:
    defaults:
      run:
        working-directory: Image.Service/
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    needs: build_img_api
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
        - run: echo ${DOCKER_TOKEN} | docker login -u ${DOCKER_LOGIN} --password-stdin
        - run: docker image build -f ../.docker/image_api.dockerfile -t image_api .
        - run: docker image tag image_api jfantauzzi/imageapi2020
        - run: docker image push jfantauzzi/imageapi2020
        - run: docker logout
  
  pack_domain_api:
    defaults:
      run:
        working-directory: Domain.Service/
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    needs: build_domain_api
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: echo ${DOCKER_TOKEN} | docker login -u ${DOCKER_LOGIN} --password-stdin
      - run: docker image build -f ../.docker/domain_api.dockerfile -t domain_api .
      - run: docker image tag domain_api jfantauzzi/domainapi2020
      - run: docker image push jfantauzzi/domainapi2020
      - run: docker logout

  pack_mvc:
    defaults:
      run:
        working-directory: StarDex.MVCClient/
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    needs: build_mvc
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: echo ${DOCKER_TOKEN} | docker login -u ${DOCKER_LOGIN} --password-stdin
      - run: docker image build -f ../.docker/MVCClient.dockerfile -t mvc .
      - run: docker image tag mvc jfantauzzi/mvc2020
      - run: docker image push jfantauzzi/mvc2020
      - run: docker logout

# DEPLOY
  deploy_angular:
    env:
      AZURE_LOGIN: ${{ secrets.AZURE_LOGIN }}
      AZURE_TENANT: ${{ secrets.AZURE_TENANT }}
      AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
    needs: pack_angular
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: az login --service-principal --username ${AZURE_LOGIN} --password ${AZURE_TOKEN} --tenant ${AZURE_TENANT}
      - run: az aks get-credentials --name stardexaks2020 --resource-group stardexaks --admin
      - run: kubectl apply --filename ./.kubernetes/angular
      - run: kubectl rollout restart --filename ./.kubernetes/angular/k8s_deployment.yaml
      - run: az logout

  deploy_image_api:
    env:
      AZURE_LOGIN: ${{ secrets.AZURE_LOGIN }}
      AZURE_TENANT: ${{ secrets.AZURE_TENANT }}
      AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
    needs: pack_image_api
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: az login --service-principal --username ${AZURE_LOGIN} --password ${AZURE_TOKEN} --tenant ${AZURE_TENANT}
      - run: az aks get-credentials --name stardexaks2020 --resource-group stardexaks --admin
      - run: kubectl apply --filename ./.kubernetes/image_api
      - run: kubectl rollout restart --filename ./.kubernetes/image_api/k8s_deployment.yaml
      - run: az logout

  deploy_mvc:
    env:
      AZURE_LOGIN: ${{ secrets.AZURE_LOGIN }}
      AZURE_TENANT: ${{ secrets.AZURE_TENANT }}
      AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
    needs: pack_mvc
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: az login --service-principal --username ${AZURE_LOGIN} --password ${AZURE_TOKEN} --tenant ${AZURE_TENANT}
      - run: az aks get-credentials --name stardexaks2020 --resource-group stardexaks --admin
      - run: kubectl apply --filename ./.kubernetes/mvc
      - run: kubectl rollout restart --filename ./.kubernetes/mvc/k8s_deployment.yaml
      - run: az logout
           
name: pipeline
    
on: push